#CLK_IN1_D definition
set_property PACKAGE_PIN D18 [get_ports CLK_IN1_D_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports CLK_IN1_D_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports CLK_IN1_D_clk_n]

#from_adc_or_DS_P
set_property IOSTANDARD LVDS_25 [get_ports {x_from_adc_or_p}]
set_property IOSTANDARD LVDS_25 [get_ports {x_from_adc_or_n}]
set_property PACKAGE_PIN E21 [get_ports {x_from_adc_or_p}]
#DATA_PINS
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_from_adc_DS_N[0]}]

set_property PACKAGE_PIN B19 [get_ports {data_from_adc_DS_P[15]}]
set_property PACKAGE_PIN J20 [get_ports {data_from_adc_DS_P[14]}]
set_property PACKAGE_PIN J16 [get_ports {data_from_adc_DS_P[13]}]
set_property PACKAGE_PIN K19 [get_ports {data_from_adc_DS_P[12]}]
set_property PACKAGE_PIN L17 [get_ports {data_from_adc_DS_P[11]}]
set_property PACKAGE_PIN P20 [get_ports {data_from_adc_DS_P[10]}]
set_property PACKAGE_PIN N17 [get_ports {data_from_adc_DS_P[9]}]
set_property PACKAGE_PIN R19 [get_ports {data_from_adc_DS_P[8]}]
set_property PACKAGE_PIN R20 [get_ports {data_from_adc_DS_P[7]}]
set_property PACKAGE_PIN J21 [get_ports {data_from_adc_DS_P[6]}]
set_property PACKAGE_PIN T16 [get_ports {data_from_adc_DS_P[5]}]
set_property PACKAGE_PIN L21 [get_ports {data_from_adc_DS_P[4]}]
set_property PACKAGE_PIN J18 [get_ports {data_from_adc_DS_P[3]}]
set_property PACKAGE_PIN M21 [get_ports {data_from_adc_DS_P[2]}]
set_property PACKAGE_PIN N22 [get_ports {data_from_adc_DS_P[1]}]
set_property PACKAGE_PIN P17 [get_ports {data_from_adc_DS_P[0]}]

#clock to ADC
set_property IOSTANDARD LVDS_25 [get_ports {clk_to_adc_DS_P}]
set_property IOSTANDARD LVDS_25 [get_ports {clk_to_adc_DS_N}]
set_property PACKAGE_PIN B21 [get_ports {clk_to_adc_DS_P}]

#other fmc connector pins
set_property IOSTANDARD LVCMOS25 [get_ports x_from_adc_calrun_fmc]
set_property IOSTANDARD LVCMOS25 [get_ports x_to_adc_cal_fmc]
set_property IOSTANDARD LVCMOS25 [get_ports x_to_adc_caldly_nscs_fmc]
set_property IOSTANDARD LVCMOS25 [get_ports x_to_adc_dclk_rst_fmc]
set_property IOSTANDARD LVCMOS25 [get_ports x_to_adc_fsr_ece_fmc]
set_property IOSTANDARD LVCMOS25 [get_ports x_to_adc_led_0]
set_property IOSTANDARD LVCMOS25 [get_ports x_to_adc_outv_slck_fmc]
set_property IOSTANDARD LVCMOS25 [get_ports x_to_adc_pd_fmc]
set_property IOSTANDARD LVCMOS25 [get_ports x_to_adc_outedge_ddr_sdata_fmc]
set_property IOSTANDARD LVCMOS25 [get_ports x_to_adc_led_1]

set_property PACKAGE_PIN B16 [get_ports x_from_adc_calrun_fmc]
set_property PACKAGE_PIN C15 [get_ports x_to_adc_cal_fmc]
set_property PACKAGE_PIN B15 [get_ports x_to_adc_caldly_nscs_fmc]
set_property PACKAGE_PIN C18 [get_ports x_to_adc_dclk_rst_fmc]
set_property PACKAGE_PIN A21 [get_ports x_to_adc_fsr_ece_fmc]
set_property PACKAGE_PIN A17 [get_ports x_to_adc_led_0]
set_property PACKAGE_PIN A16 [get_ports x_to_adc_led_1]
set_property PACKAGE_PIN C17 [get_ports x_to_adc_outedge_ddr_sdata_fmc]
set_property PACKAGE_PIN A22 [get_ports x_to_adc_outv_slck_fmc]
set_property PACKAGE_PIN B17 [get_ports x_to_adc_pd_fmc]
